# Generated by Django 6.0.6 on 2026-06-13 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_donation_date', models.DateField(blank=True, help_text='تاريخ آخر تبرع — يُحدَّث تلقائياً بعد كل عملية', null=True)),
                ('total_donations', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True, help_text='False = ضمن فترة الحظر الصحي (90 يوماً)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
