# Generated by Django 6.0.6 on 2026-06-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='إرسال بريد إلكتروني عند وجود حالة عاجلة تطابق فصيلة الدم', verbose_name='إشعارات البريد الإلكتروني'),
        ),
    ]
