# Generated by Django 6.0.6 on 2026-06-13 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name_hidden', models.CharField(help_text='سري تماماً — لا يظهر في أي واجهة مواجهة للمتبرعين', max_length=100)),
                ('blood_type_needed', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('bags_required', models.IntegerField(default=1)),
                ('bags_received', models.IntegerField(default=0)),
                ('hospital_branch_address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'عاجل / مستمر'), ('fulfilled', 'تم توفير الكمية'), ('closed', 'مغلق / ملغي')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(limit_choices_to={'role': 'hospital'}, on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
