# Generated by Django 6.0.6 on 2026-06-13 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'يوجد مستخدم مسجل باسم المستخدم هذا بالفعل.'}, help_text='مطلوب. 150 حرفاً أو أقل. الأحرف، الأرقام، المسافات، والرموز @/./+/-/_ فقط.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(flags=0, message='أدخل اسم مستخدم صالح. يمكن أن يحتوي هذا الحقل على أحرف، أرقام، مسافات، والرموز @/./+/-/_ فقط.', regex='^[\\w.@+-\\s]+\\Z')], verbose_name='اسم المستخدم'),
        ),
    ]
