# Generated by Django 6.0.6 on 2026-06-13 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('going', 'في الطريق إلى المستشفى'), ('completed', 'تم التبرع بنجاح'), ('failed', 'لم يتم التبرع')], default='going', max_length=20)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='يُملأ تلقائياً من الـ Signal عند تأكيد الموظف', null=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='blood_requests.bloodrequest')),
                ('donor', models.ForeignKey(limit_choices_to={'role': 'donor'}, on_delete=django.db.models.deletion.CASCADE, related_name='my_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-donated_at'],
                'unique_together': {('blood_request', 'donor')},
            },
        ),
    ]
